name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile-target
      run: ./start.sh -c
    - name: compile-library
      run: ./start.sh -cl
    - name: run-tests
      run: ./start.sh -ct
